
AWSTemplateFormatVersion : '2010-09-09'
Transform:
    - AWS::Serverless-2016-10-31
    
Description: Lambda Cloudformation
Resources:
    GetUser:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: get-user-smm
            Handler: user.getUser
            Runtime: python3.6
            CodeUri: package/
            Environment:
              Variables:
                USERS_TABLE: !Ref Userstable
            
            Events:
              GetUsers:
                Type: Api
                Properties:
                  RestApiId: !Ref MyAPI
                  Path: /user
                  Method: GET
            
    PutUser:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: put-user-smm
            Handler: user.putUser
            Runtime: python3.6
            CodeUri: package/
            Environment:
              Variables:
                USERS_TABLE: !Ref Userstable
                            
            Events:
              GetUsers:
                Type: Api
                Properties:
                  RestApiId: !Ref MyAPI
                  Path: /user
                  Method: PUT
            
                
                
    
    MyAPI:
        Type: AWS::Serverless::Api
        Properties:
          Name: user-api
          StageName: prod
          DefinitionBody:
            Fn::Transform:
              Name: AWS::Include
              Parameters:
                Location: swagger.yaml
                   
    #Mytable:
    #  Type: AWS::Serverless::SimpleTable
    #  Properties:
    #    PrimaryKey:
    #      Name: pk
    #      Type: String
        

    Userstable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: users-table
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          AttributeDefinitions:
            - AttributeName: pk
              AttributeType: S
            - AttributeName: sk
              AttributeType: N